SELECT 
INITIATIVE_NAME
,PROJECT_NAME_CORR
,SHIPPING_TYPE
,SEASON_YEAR
,DATA_SOURCE
,WBKZ
,coalesce(PAGES_TOTAL,0) AS PAGES_TOTAL
,CIRCULATION_PLAN
,CIRCULATION_ACTUAL
,coalesce(KATALOG_GEWICHT_GESAMT,0) AS KATALOG_GEWICHT_GESAMT
,KOSTENARTENBESCHREIBUNG
,COSTS
FROM (

SELECT DISTINCT
INITIATIVE_NAME
,CASE 
   WHEN PROJECT_NAME REGEXP_LIKE '^\d{2}GJ_.*' THEN REGEXP_REPLACE(PROJECT_NAME,'(?:^[^_]+_)([^_\n]+)(?:_*.*)','\1')
   ELSE PROJECT_NAME 
END  AS PROJECT_NAME_CORR
,LOWER(PWM_SHIPPING_TYPE)  AS SHIPPING_TYPE
,CAST(REGEXP_SUBSTR(PWM_SEASON_FINANCIAL_YEAR, '^\d\d') as DECIMAL(18,0)) AS SEASON
,CASE
   WHEN LOCAL.SHIPPING_TYPE IS NULL THEN HASH_MD5(LOCAL.PROJECT_NAME_CORR,CAST(LOCAL.SEASON AS VARCHAR(3))) 
   ELSE  HASH_MD5(LOCAL.PROJECT_NAME_CORR,CAST(LOCAL.SEASON AS VARCHAR(3)), LOCAL.SHIPPING_TYPE) 
END AS ID
,PWM_SEASON_FINANCIAL_YEAR AS SEASON_YEAR
,'OPP Creation' AS DATA_SOURCE
,PWM_OPP_WBKZ AS WBKZ
,PWM_PAGES_TOTAL AS PAGES_TOTAL
,PWM_CIRCULATION_PLAN AS CIRCULATION_PLAN
,PWM_CIRCULATION_ACTUAL AS CIRCULATION_ACTUAL
,CREATION_COST.KOSTENARTENBES AS KOSTENARTENBESCHREIBUNG
,CREATION_COST.WERT_OVERALL AS COSTS
,PWM_NEW_TEST AS IS_TEST

        ,CASE 
                WHEN PWM_SHIPPING_TYPE='Package' THEN
        (((PWM_FORMAT_HEIGHT/100*PWM_FORMAT_WIDTH/100*PWM_CONTENT_SURFACE_WEIGHT*PWM_CONTENT_NUMBER_PAGES/2)+(PWM_FORMAT_HEIGHT/100*PWM_FORMAT_WIDTH/100*PWM_COVER_SURFACE_WEIGHT*PWM_COVER_NUMBER_PAGES/2))*1.04)+5  
        ELSE ((PWM_FORMAT_HEIGHT/100*PWM_FORMAT_WIDTH/100*PWM_CONTENT_SURFACE_WEIGHT*PWM_CONTENT_NUMBER_PAGES/2)+(PWM_FORMAT_HEIGHT/100*PWM_FORMAT_WIDTH/100*PWM_COVER_SURFACE_WEIGHT*PWM_COVER_NUMBER_PAGES/2))*1.04
        END AS KATALOG_GEWICHT_GESAMT

FROM PRD_BIWA_KATALOGREPORTING.MARKETINGPLANNING_MARMIND_CHANNELMARKETING_PRINT_EXPLODED 
LEFT JOIN PRD_MART_OM_RELI.PRINT_CATALOG_CREATION_COST AS CREATION_COST
ON PWM_OPP_WBKZ = CREATION_COST.AUFTRAG

UNION ALL 

SELECT DISTINCT
INITIATIVE_NAME
,CASE 
   WHEN PROJECT_NAME REGEXP_LIKE '^\d{2}GJ_.*' THEN REGEXP_REPLACE(PROJECT_NAME,'(?:^[^_]+_)([^_\n]+)(?:_*.*)','\1')
   ELSE PROJECT_NAME 
END  AS PROJECT_NAME_CORR
,LOWER(PWM_SHIPPING_TYPE)  AS SHIPPING_TYPE
,CAST(REGEXP_SUBSTR(PWM_SEASON_FINANCIAL_YEAR, '^\d\d') as DECIMAL(18,0)) AS SEASON
,CASE
   WHEN LOCAL.SHIPPING_TYPE IS NULL THEN HASH_MD5(LOCAL.PROJECT_NAME_CORR,CAST(LOCAL.SEASON AS VARCHAR(3))) 
   ELSE  HASH_MD5(LOCAL.PROJECT_NAME_CORR,CAST(LOCAL.SEASON AS VARCHAR(3)), LOCAL.SHIPPING_TYPE) 
END AS ID
,PWM_SEASON_FINANCIAL_YEAR AS SEASON_YEAR
,'PPC Creative' AS DATA_SOURCE
,PWM_PPC_WBKZ AS WBKZ
,PWM_PAGES_TOTAL AS PAGES_TOTAL
,PWM_CIRCULATION_PLAN AS CIRCULATION_PLAN
,PWM_CIRCULATION_ACTUAL AS CIRCULATION_ACTUAL
,CREATIV_COST.KOSTENARTENBES AS KOSTENARTENBESCHREIBUNG
,CREATIV_COST.WERT_OVERALL AS COSTS
,PWM_NEW_TEST AS IS_TEST

        ,CASE 
                WHEN PWM_SHIPPING_TYPE='Package' THEN
        (((PWM_FORMAT_HEIGHT/100*PWM_FORMAT_WIDTH/100*PWM_CONTENT_SURFACE_WEIGHT*PWM_CONTENT_NUMBER_PAGES/2)+(PWM_FORMAT_HEIGHT/100*PWM_FORMAT_WIDTH/100*PWM_COVER_SURFACE_WEIGHT*PWM_COVER_NUMBER_PAGES/2))*1.04)+5  
        ELSE ((PWM_FORMAT_HEIGHT/100*PWM_FORMAT_WIDTH/100*PWM_CONTENT_SURFACE_WEIGHT*PWM_CONTENT_NUMBER_PAGES/2)+(PWM_FORMAT_HEIGHT/100*PWM_FORMAT_WIDTH/100*PWM_COVER_SURFACE_WEIGHT*PWM_COVER_NUMBER_PAGES/2))*1.04
        END AS KATALOG_GEWICHT_GESAMT

FROM  PRD_BIWA_KATALOGREPORTING.MARKETINGPLANNING_MARMIND_CHANNELMARKETING_PRINT_EXPLODED 
LEFT JOIN PRD_MART_OM_RELI.PRINT_CATALOG_CREATIVE_COST AS CREATIV_COST
ON PWM_PPC_WBKZ = CREATIV_COST.AUFTRAG

UNION ALL

SELECT DISTINCT
INITIATIVE_NAME
,CASE 
   WHEN PROJECT_NAME REGEXP_LIKE '^\d{2}GJ_.*' THEN REGEXP_REPLACE(PROJECT_NAME,'(?:^[^_]+_)([^_\n]+)(?:_*.*)','\1')
   ELSE PROJECT_NAME 
END  AS PROJECT_NAME_CORR
,LOWER(PWM_SHIPPING_TYPE)  AS SHIPPING_TYPE
,CAST(REGEXP_SUBSTR(PWM_SEASON_FINANCIAL_YEAR, '^\d\d') as DECIMAL(18,0)) AS SEASON
,CASE
   WHEN LOCAL.SHIPPING_TYPE IS NULL THEN HASH_MD5(LOCAL.PROJECT_NAME_CORR,CAST(LOCAL.SEASON AS VARCHAR(3))) 
   ELSE  HASH_MD5(LOCAL.PROJECT_NAME_CORR,CAST(LOCAL.SEASON AS VARCHAR(3)), LOCAL.SHIPPING_TYPE) 
END AS ID
,PWM_SEASON_FINANCIAL_YEAR AS SEASON_YEAR
,'OPP Shipping' AS DATA_SOURCE
,PWM_WBKZ AS WBKZ
,PWM_PAGES_TOTAL AS PAGES_TOTAL
,PWM_CIRCULATION_PLAN AS CIRCULATION_PLAN
,PWM_CIRCULATION_ACTUAL AS CIRCULATION_ACTUAL
,SHIPPING_COST.KOSTENARTENBES AS KOSTENARTENBESCHREIBUNG
,SHIPPING_COST.WERT_OVERALL AS COSTS
,PWM_NEW_TEST AS IS_TEST

        ,CASE 
                WHEN PWM_SHIPPING_TYPE='Package' THEN
        (((PWM_FORMAT_HEIGHT/100*PWM_FORMAT_WIDTH/100*PWM_CONTENT_SURFACE_WEIGHT*PWM_CONTENT_NUMBER_PAGES/2)+(PWM_FORMAT_HEIGHT/100*PWM_FORMAT_WIDTH/100*PWM_COVER_SURFACE_WEIGHT*PWM_COVER_NUMBER_PAGES/2))*1.04)+5  
        ELSE ((PWM_FORMAT_HEIGHT/100*PWM_FORMAT_WIDTH/100*PWM_CONTENT_SURFACE_WEIGHT*PWM_CONTENT_NUMBER_PAGES/2)+(PWM_FORMAT_HEIGHT/100*PWM_FORMAT_WIDTH/100*PWM_COVER_SURFACE_WEIGHT*PWM_COVER_NUMBER_PAGES/2))*1.04
        END AS KATALOG_GEWICHT_GESAMT

FROM PRD_BIWA_KATALOGREPORTING.MARKETINGPLANNING_MARMIND_CHANNELMARKETING_PRINT_EXPLODED 
LEFT JOIN PRD_MART_OM_RELI.PRINT_CATALOG_SHIPPING_COST AS SHIPPING_COST
ON PWM_WBKZ = SHIPPING_COST.AUFTRAG
)
--WHERE INITIATIVE_NAME = '23GJ_OV819'
--WHERE PROJECT_NAME_CORR like '%Sommer-Highlights%'
--AND SHIPPING_TYPE = 'package'
WHERE wbkz IS NOT NULL
group by 1,2,3,4,5,6,7,8,9,10,11,12

;