WITH STA_NEXT AS (

SELECT DISTINCT
INITIATIVE_NAME
,CASE 
   WHEN PROJECT_NAME REGEXP_LIKE '^\d{2}GJ_.*' THEN REGEXP_REPLACE(PROJECT_NAME,'(?:^[^_]+_)([^_\n]+)(?:_*.*)','\1')
   ELSE PROJECT_NAME 
END  AS PROJECT_NAME_CORR
,LOWER(PWM_SHIPPING_TYPE)  AS SHIPPING_TYPE
,CAST(REGEXP_SUBSTR(PWM_SEASON_FINANCIAL_YEAR, '^\d\d') as DECIMAL(18,0)) AS SEASON
,CASE
   WHEN LOCAL.SHIPPING_TYPE IS NULL THEN HASH_MD5(LOCAL.PROJECT_NAME_CORR,CAST(LOCAL.SEASON AS VARCHAR(3))) 
   ELSE  HASH_MD5(LOCAL.PROJECT_NAME_CORR,CAST(LOCAL.SEASON AS VARCHAR(3)), LOCAL.SHIPPING_TYPE) 
END AS ID
,PWM_OPP_WBKZ AS OPP_WBKZ
,PWM_PPC_WBKZ AS PPC_WBKZ
,PWM_WBKZ AS VERSAND_WBKZ
,PWM_PAGES_TOTAL AS PAGES_TOTAL
,PWM_CIRCULATION_PLAN AS CIRCULATION_PLAN
,PWM_CIRCULATION_ACTUAL AS CIRCULATION_ACTUAL
,PWM_NEW_TEST AS IS_TEST
FROM PRD_BIWA_KATALOGREPORTING.MARKETINGPLANNING_MARMIND_CHANNELMARKETING_PRINT_EXPLODED 

WHERE LOCAL.SEASON IN (

SELECT 
CASE 
WHEN EXTRACT(MONTH FROM CURRENT_DATE) < 3 THEN CAST(TO_CHAR(CURRENT_DATE, 'YY') AS DECIMAL(18,0)) - 1
ELSE CAST(TO_CHAR(CURRENT_DATE, 'YY') AS DECIMAL(18,0))
END AS SEASON ) + 1

AND LOWER(PROJECT_NAME) NOT LIKE '%aufleger%'
AND IS_PROJECT_ACTIVE = TRUE
AND PWM_TAKER_CROSS_SELLING IS NULL
AND IS_PROJECT_ARCHIVED = FALSE
), STA_LAST AS (

SELECT DISTINCT
INITIATIVE_NAME
,CASE 
   WHEN PROJECT_NAME REGEXP_LIKE '^\d{2}GJ_.*' THEN REGEXP_REPLACE(PROJECT_NAME,'(?:^[^_]+_)([^_\n]+)(?:_*.*)','\1')
   ELSE PROJECT_NAME 
END  AS PROJECT_NAME_CORR
,LOWER(PWM_SHIPPING_TYPE)  AS SHIPPING_TYPE
--, REPLACE(LOCAL.PROJECT_NAME_CORR, 'AKTIONSFORMAT', 'PLATTFORMFORMAT') AS PROJECT_NAME_MIG
,CAST(REGEXP_SUBSTR(PWM_SEASON_FINANCIAL_YEAR, '^\d\d') as DECIMAL(18,0)) AS SEASON
,CASE
   WHEN LOCAL.SHIPPING_TYPE IS NULL THEN HASH_MD5(LOCAL.PROJECT_NAME_CORR,CAST(LOCAL.SEASON AS VARCHAR(3))) 
   ELSE  HASH_MD5(LOCAL.PROJECT_NAME_CORR,CAST(LOCAL.SEASON + 1 AS VARCHAR(3)), LOCAL.SHIPPING_TYPE) 
END AS ID
,PWM_OPP_WBKZ AS OPP_WBKZ
,PWM_PPC_WBKZ AS PPC_WBKZ
,PWM_WBKZ AS VERSAND_WBKZ
,PWM_PAGES_TOTAL AS PAGES_TOTAL
,PWM_CIRCULATION_PLAN AS CIRCULATION_PLAN
,PWM_CIRCULATION_ACTUAL AS CIRCULATION_ACTUAL
,PWM_NEW_TEST AS IS_TEST
FROM PRD_BIWA_KATALOGREPORTING.MARKETINGPLANNING_MARMIND_CHANNELMARKETING_PRINT_EXPLODED 
WHERE LOCAL.SEASON IN (

SELECT 
CASE 
WHEN EXTRACT(MONTH FROM CURRENT_DATE) < 3 THEN CAST(TO_CHAR(CURRENT_DATE, 'YY') AS DECIMAL(18,0)) - 1
ELSE CAST(TO_CHAR(CURRENT_DATE, 'YY') AS DECIMAL(18,0))
END AS SEASON )

AND LOWER(PROJECT_NAME) NOT LIKE '%aufleger%'

AND IS_PROJECT_ACTIVE = TRUE
AND PWM_TAKER_CROSS_SELLING IS NULL
AND IS_PROJECT_ARCHIVED = FALSE
)  
-----------------
SELECT 
STA_LAST.PROJECT_NAME_CORR AS PROJECT_NAME,
STA_LAST.SHIPPING_TYPE AS SHIPPING_TYPE,

STA_LAST.SEASON AS LAST_SEASION,
STA_LAST.PAGES_TOTAL AS LAST_PAGES_TOTAL,
STA_LAST.CIRCULATION_ACTUAL AS LAST_CIRCULATION_ACTUAL,
STA_LAST.CIRCULATION_PLAN AS LAST_CIRCULATION_PLAN,
--STA_LAST.PPC_WBKZ AS LAST_CREATIV_WBKZ,
--CREATIV_COST.KOSTENARTENBES,
--CREATIV_COST.WERT_OVERALL,
--STA_LAST.OPP_WBKZ AS LAST_CREATION_WBKZ,
--CREATION_COST.KOSTENARTENBES,
--REATION_COST.WERT_OVERALL,

STA_NEXT.SEASON AS THIS_SEASON,
STA_NEXT.PAGES_TOTAL AS THIS_PAGES_TOTAL,
STA_NEXT.CIRCULATION_ACTUAL AS THIS_CIRCULATION_ACTUAL,
STA_NEXT.CIRCULATION_PLAN AS THIS_CIRCULATION_PLAN
--STA_NEXT.PPC_WBKZ AS THIS_CREATIV_WBKZ

FROM STA_LAST
LEFT JOIN STA_NEXT
ON STA_LAST.ID = STA_NEXT.ID
-- Kreativ Kosten
--LEFT JOIN PRD_MART_OM_RELI.PRINT_CATALOG_CREATIVE_COST AS CREATIV_COST
--ON STA_LAST.PPC_WBKZ = CREATIV_COST.AUFTRAG
-- Erstellungs Kosten
--LEFT JOIN PRD_MART_OM_RELI.PRINT_CATALOG_CREATION_COST AS CREATION_COST
--ON STA_LAST.OPP_WBKZ = CREATION_COST.AUFTRAG
WHERE UPPER(LOCAL.PROJECT_NAME) = 'BEACHTIME' 
;


desc PRD_MART_OM_RELI.PRINT_CATALOG_CREATIVE_COST




-- with calculation
SELECT 
        PWM_SEASON_FINANCIAL_YEAR AS PWM_SEASON_FINANCIAL_YEAR
        ,PWM_OV_NUMBER AS PWM_OV_NUMBER
        ,INITIATIVE_ENTITY_NUMBER AS INITIATIVE_ENTITY_NUMBER
        ,INITIATIVE_NAME AS INITIATIVE_NAME
        ,PROJECT_ENTITY_NUMBER AS PROJECT_ENTITY_NUMBER
        ,PROJECT_NAME AS PROJECT_NAME
        ,INITIATIVE_PRINT_DATE_SHIPPING AS VERSANDDATUM
        ,sum(PWM_CIRCULATION_PLAN) AS PWM_CIRCULATION_PLAN --drin lassen
        ,sum(PWM_CIRCULATION_ACTUAL) AS PWM_CIRCULATION_ACTUAL --Prüfen, wann Daten vorhanden sind    
        ,CASE 
                WHEN PWM_SHIPPING_TYPE='Package' THEN
        (((PWM_FORMAT_HEIGHT/100*PWM_FORMAT_WIDTH/100*PWM_CONTENT_SURFACE_WEIGHT*PWM_CONTENT_NUMBER_PAGES/2)+(PWM_FORMAT_HEIGHT/100*PWM_FORMAT_WIDTH/100*PWM_COVER_SURFACE_WEIGHT*PWM_COVER_NUMBER_PAGES/2))*1.04)+5  
        ELSE ((PWM_FORMAT_HEIGHT/100*PWM_FORMAT_WIDTH/100*PWM_CONTENT_SURFACE_WEIGHT*PWM_CONTENT_NUMBER_PAGES/2)+(PWM_FORMAT_HEIGHT/100*PWM_FORMAT_WIDTH/100*PWM_COVER_SURFACE_WEIGHT*PWM_COVER_NUMBER_PAGES/2))*1.04
        END AS KATALOG_GEWICHT_GESAMT
        ,NETTO_WERT

FROM PRD_BIWA_KATALOGREPORTING.MARKETINGPLANNING_MARMIND_CHANNELMARKETING_PRINT m
LEFT JOIN PRD_MART_OM_RELI.V_POST_KONDITIONEN p
ON      CASE 
                WHEN PWM_SHIPPING_TYPE='Package' THEN
        (((PWM_FORMAT_HEIGHT/100*PWM_FORMAT_WIDTH/100*PWM_CONTENT_SURFACE_WEIGHT*PWM_CONTENT_NUMBER_PAGES/2)+(PWM_FORMAT_HEIGHT/100*PWM_FORMAT_WIDTH/100*PWM_COVER_SURFACE_WEIGHT*PWM_COVER_NUMBER_PAGES/2))*1.04)+5  
        ELSE ((PWM_FORMAT_HEIGHT/100*PWM_FORMAT_WIDTH/100*PWM_CONTENT_SURFACE_WEIGHT*PWM_CONTENT_NUMBER_PAGES/2)+(PWM_FORMAT_HEIGHT/100*PWM_FORMAT_WIDTH/100*PWM_COVER_SURFACE_WEIGHT*PWM_COVER_NUMBER_PAGES/2))*1.04
        END Between MIN_GEW AND MAX_GEW
AND Extract(Year FROM INITIATIVE_PRINT_DATE_SHIPPING)*100+Extract(Month FROM INITIATIVE_PRINT_DATE_SHIPPING) =MONAT

--WHERE PROJECT_NAME like '%Plattformformat%'

WHERE IS_PROJECT_ACTIVE = TRUE
AND INSTR(UPPER(INITIATIVE_NAME), 'HEINE') = 0
AND INSTR(UPPER(INITIATIVE_NAME), '_LA') = 0
AND PWM_TAKER_CROSS_SELLING IS NULL
AND IS_PROJECT_ARCHIVED = FALSE
AND PWM_SEASON_FINANCIAL_YEAR NOT IN ('22FS','22HW','23GJ')
AND UPPER(ACTION_PBT_AD_COMPONENTS) <> 'UMSCHLAG'
AND pwm_print_ad              = 'Katalog'

GROUP BY 1,2,3,4,5,6,7,10,11

