WITH STA_NEXT AS (

SELECT DISTINCT
INITIATIVE_NAME
,CASE 
   WHEN PROJECT_NAME REGEXP_LIKE '^\d{2}GJ_.*' THEN REGEXP_REPLACE(PROJECT_NAME,'(?:^[^_]+_)([^_\n]+)(?:_*.*)','\1')
   ELSE PROJECT_NAME 
END  AS PROJECT_NAME_CORR
,LOWER(PWM_SHIPPING_TYPE)  AS SHIPPING_TYPE
,CAST(REGEXP_SUBSTR(PWM_SEASON_FINANCIAL_YEAR, '^\d\d') as DECIMAL(18,0)) AS SEASON
,CASE
   WHEN LOCAL.SHIPPING_TYPE IS NULL THEN HASH_MD5(LOCAL.PROJECT_NAME_CORR,CAST(LOCAL.SEASON AS VARCHAR(3))) 
   ELSE  HASH_MD5(LOCAL.PROJECT_NAME_CORR,CAST(LOCAL.SEASON AS VARCHAR(3)), LOCAL.SHIPPING_TYPE) 
END AS ID
,PWM_OPP_WBKZ AS OPP_WBKZ
,PWM_PPC_WBKZ AS PPC_WBKZ
,PWM_WBKZ AS VERSAND_WBKZ
,PWM_PAGES_TOTAL AS PAGES_TOTAL
,PWM_NEW_TEST AS IS_TEST
FROM PRD_BIWA_KATALOGREPORTING.MARKETINGPLANNING_MARMIND_CHANNELMARKETING_PRINT_EXPLODED 

WHERE LOCAL.SEASON IN (

SELECT 
CASE 
WHEN EXTRACT(MONTH FROM CURRENT_DATE) < 3 THEN CAST(TO_CHAR(CURRENT_DATE, 'YY') AS DECIMAL(18,0)) - 1
ELSE CAST(TO_CHAR(CURRENT_DATE, 'YY') AS DECIMAL(18,0))
END AS SEASON ) + 1

AND LOWER(PROJECT_NAME) NOT LIKE '%aufleger%'
AND IS_PROJECT_ACTIVE = TRUE
AND PWM_TAKER_CROSS_SELLING IS NULL
AND IS_PROJECT_ARCHIVED = FALSE
), STA_LAST AS (

SELECT DISTINCT
INITIATIVE_NAME
,CASE 
   WHEN PROJECT_NAME REGEXP_LIKE '^\d{2}GJ_.*' THEN REGEXP_REPLACE(PROJECT_NAME,'(?:^[^_]+_)([^_\n]+)(?:_*.*)','\1')
   ELSE PROJECT_NAME 
END  AS PROJECT_NAME_CORR
,LOWER(PWM_SHIPPING_TYPE)  AS SHIPPING_TYPE
--, REPLACE(LOCAL.PROJECT_NAME_CORR, 'AKTIONSFORMAT', 'PLATTFORMFORMAT') AS PROJECT_NAME_MIG
,CAST(REGEXP_SUBSTR(PWM_SEASON_FINANCIAL_YEAR, '^\d\d') as DECIMAL(18,0)) AS SEASON
,CASE
   WHEN LOCAL.SHIPPING_TYPE IS NULL THEN HASH_MD5(LOCAL.PROJECT_NAME_CORR,CAST(LOCAL.SEASON AS VARCHAR(3))) 
   ELSE  HASH_MD5(LOCAL.PROJECT_NAME_CORR,CAST(LOCAL.SEASON + 1 AS VARCHAR(3)), LOCAL.SHIPPING_TYPE) 
END AS ID
,PWM_OPP_WBKZ AS OPP_WBKZ
,PWM_PPC_WBKZ AS PPC_WBKZ
,PWM_WBKZ AS VERSAND_WBKZ
,PWM_PAGES_TOTAL AS PAGES_TOTAL
,PWM_NEW_TEST AS IS_TEST
FROM PRD_BIWA_KATALOGREPORTING.MARKETINGPLANNING_MARMIND_CHANNELMARKETING_PRINT_EXPLODED 
WHERE LOCAL.SEASON IN (

SELECT 
CASE 
WHEN EXTRACT(MONTH FROM CURRENT_DATE) < 3 THEN CAST(TO_CHAR(CURRENT_DATE, 'YY') AS DECIMAL(18,0)) - 1
ELSE CAST(TO_CHAR(CURRENT_DATE, 'YY') AS DECIMAL(18,0))
END AS SEASON )

AND LOWER(PROJECT_NAME) NOT LIKE '%aufleger%'

AND IS_PROJECT_ACTIVE = TRUE
AND PWM_TAKER_CROSS_SELLING IS NULL
AND IS_PROJECT_ARCHIVED = FALSE
)  
-----------------
SELECT 
STA_LAST.PROJECT_NAME_CORR AS PROJECT_NAME,
STA_LAST.SHIPPING_TYPE AS SHIPPING_TYPE,
STA_LAST.SEASON AS LAST_SEASION,
STA_LAST.PAGES_TOTAL AS LAST_PAGES_TOTAL,
STA_LAST.PPC_WBKZ AS LAST_CREATIV_WBKZ,
CREATIV_COST.KOSTENARTENBES,
CREATIV_COST.WERT_OVERALL,
STA_NEXT.SEASON AS THIS_SEASON,
STA_NEXT.PAGES_TOTAL AS THIS_PAGES_TOTAL,
STA_NEXT.PPC_WBKZ AS THIS_CREATIV_WBKZ

FROM STA_LAST
LEFT JOIN STA_NEXT
ON STA_LAST.ID = STA_NEXT.ID
LEFT JOIN PRD_MART_OM_RELI.PRINT_CATALOG_CREATIVE_COST AS CREATIV_COST
ON STA_LAST.PPC_WBKZ = CREATIV_COST.AUFTRAG
--WHERE LOCAL.PROJECT_NAME = 'Beachtime' 
;