WITH CTE_PC AS (
    SELECT DISTINCT
        CHANNEL_NAME
        , PLANNING_CONTEXT_CODE
        , PLANNING_CONTEXT_NAME
        , CAMP_ID
    FROM
        PRD_BIWA_ONLINEMARKETINGSTEUERUNG.ONLINEMARKETINGSTEUERUNG_CAMPID_TO_KAMEL_PLANNINGCONTEXT
        --${EXAENV}_BIWD_ONLINEMARKETINGSTEUERUNG_CONS.ONLINEMARKETINGSTEUERUNG_CAMPID_TO_KAMEL_PLANNINGCONTEXT
)

, PRT_PC AS (
-- Tageskosten AWIN (AWIN UND AWIN2)
    SELECT
        TO_DATE(DAT.ORDER_TIMESTAMP) AS REPORTING_DATE
        , COALESCE(CTE_PC.PLANNING_CONTEXT_CODE,'AN.MP-A.C') AS PLANNING_CONTEXT_CODE
        , COALESCE(CTE_PC.PLANNING_CONTEXT_NAME,'AWIN') AS PLANNING_CONTEXT_NAME
        , 'Affiliates' AS CHANNEL
        , DAT.CAMP_ID AS CAMP_ID
        , '${EXAENV}_BIWD_ONLINEMARKETINGSTEUERUNG_CONS.AFFILIATE_COSTS_AWIN' AS SOURCE_SYSTEM
        , 0 AS IMPRESSIONS
        , 0 AS CLICKS
        , DAT.NW_PROVISION_HR + DAT.NW_NETWORKFEE_HR AS COST_EURO
    FROM
        PRD_BIWA_ONLINEMARKETINGREPORTING.BASAP_AFFILIATE_COSTS_AWIN AS DAT
        --${EXAENV}_BIWD_ONLINEMARKETINGSTEUERUNG_CONS.BASAP_AFFILIATE_COSTS_AWIN AS DAT
    LEFT JOIN CTE_PC
        ON DAT.CAMP_ID = CTE_PC.CAMP_ID
    WHERE
        LOCAL.COST_EURO != 0
        AND LOCAL.REPORTING_DATE BETWEEN ADD_YEARS(CURRENT_DATE,-2) AND CURRENT_DATE
    -----------
    UNION ALL
    -----------
    --Tagekosten Private Network (BONI + CPC)
    SELECT
        TO_DATE(DAT.ORDER_TIMESTAMP) AS REPORTING_DATE
        , COALESCE(CTE_PC.PLANNING_CONTEXT_CODE,'PN.MP-A.C') AS PLANNING_CONTEXT_CODE
        , COALESCE(CTE_PC.PLANNING_CONTEXT_NAME,'Private Network') AS PLANNING_CONTEXT_NAME
        , 'Affiliates' AS CHANNEL
        , DAT.CAMP_ID AS CAMP_ID
        , '${EXAENV}_BIWD_ONLINEMARKETINGSTEUERUNG_CONS.AFFILIATE_COSTS_EASYMARKETING' AS SOURCE_SYSTEM
        , 0 AS IMPRESSIONS
        , 0 AS CLICKS
        , DAT.NW_PROVISION_HR AS COST_EURO
    FROM
        PRD_BIWA_ONLINEMARKETINGREPORTING.BASAP_AFFILIATE_COSTS_EASYMARKETING AS DAT
        --${EXAENV}_BIWD_ONLINEMARKETINGSTEUERUNG_CONS.BASAP_AFFILIATE_COSTS_EASYMARKETING AS DAT
    LEFT JOIN CTE_PC
        ON DAT.CAMP_ID = CTE_PC.CAMP_ID
    WHERE
        LOCAL.COST_EURO != 0
        AND LOCAL.REPORTING_DATE BETWEEN ADD_YEARS(CURRENT_DATE,-2) AND CURRENT_DATE
    -----------
    UNION ALL
    -----------
    -- Fixkosten
    SELECT
        DIM.DATUM AS REPORTING_DATE
        , COALESCE(CTE_PC.PLANNING_CONTEXT_CODE,'PN.MP-A.C') AS PLANNING_CONTEXT_CODE
        , COALESCE(CTE_PC.PLANNING_CONTEXT_NAME,'Private Network') AS PLANNING_CONTEXT_NAME
        , 'Affiliates' AS CHANNEL
        ,  DAT.CAMPAIGN AS CAMP_ID
        , '${EXAENV}_BIWA_ONLINEMARKETINGSTEUERUNG.AMOR_AFFILIATE_MARKETING_KPI_SA_PERSISTENT' AS SOURCE_SYSTEM
        , 0 AS IMPRESSIONS
        , 0 AS CLICKS
        , (DAT.COST_EURO / DAT.DURATION_IN_DAYS)AS COST_EURO
    FROM (
        SELECT ADD_DAYS(DATE '2017-01-01', LEVEL-1) AS DATUM FROM DUAL
        CONNECT BY LEVEL <= DAYS_BETWEEN('2049-01-01','2017-01-01')+1
    ) AS DIM    
               
    LEFT JOIN 
        PRD_BIWA_ONLINEMARKETINGREPORTING.AMOR3_AFFILIATE_FIXCOST AS DAT
        --${EXAENV}_BIWD_ONLINEMARKETINGSTEUERUNG_CONS.AMOR3_AFFILIATE_FIXCOST AS DAT
        ON DIM.DATUM BETWEEN DAT.START_DATE AND DAT.END_DATE
        
    LEFT JOIN CTE_PC
        ON DAT.CAMPAIGN = CTE_PC.CAMP_ID
    WHERE
        DAT.ADDITIONAL_COSTS = 'true'
        AND LOCAL.REPORTING_DATE BETWEEN ADD_YEARS(CURRENT_DATE,-2) AND CURRENT_DATE
    -----------
    UNION ALL
    -----------
    -- Clicks für AWIN und ESAY
    SELECT
        TO_DATE(CONVERT_TZ(C.EVENT_CREATED_AT_UTC,'UTC','CET')) AS REPORTING_DATE
        , CTE_PC.PLANNING_CONTEXT_CODE AS PLANNING_CONTEXT_CODE
        , CTE_PC.PLANNING_CONTEXT_NAME AS PLANNING_CONTEXT_NAME
        , 'Affiliates' AS CHANNEL
        , CA.CAMPAIGN_ID AS CAMP_ID
        , '${EXAENV}_BIWA_ONLINEMARKETINGREPORTING.TRACKINGDATA_EXTERNAL_CALL_OTTODE_S' AS SOURCE_SYSTEM
        , 0 AS IMPRESSIONS
        , 1 AS CLICKS
        , 0 AS COST_EURO
    FROM
        PRD_BIWA_ONLINEMARKETINGREPORTING.TRACKINGDATA_EXTERNAL_CALL_OTTODE_S AS C
        --${EXAENV}_BIWD_ONLINEMARKETINGSTEUERUNG_CONS.TRACKINGDATA_EXTERNAL_CALL_OTTODE_S AS C
    INNER JOIN
        PRD_BIWA_ONLINEMARKETINGREPORTING.TRACKINGDATA_EXTERNAL_CALL_OTTODE_TO_CAMPAIGN_L AS L
        --${EXAENV}_BIWD_ONLINEMARKETINGSTEUERUNG_CONS.TRACKINGDATA_EXTERNAL_CALL_OTTODE_TO_CAMPAIGN_L AS L
        ON      C.EXTERNAL_CALL_OTTODE_H_SK = L.EXTERNAL_CALL_OTTODE_H_SK
    INNER JOIN
        PRD_BIWA_ONLINEMARKETINGSTEUERUNG.ONLINEMARKETINGSTEUERUNG_CAMPAIGN_H AS CA
        --${EXAENV}_BIWD_ONLINEMARKETINGSTEUERUNG_CONS.ONLINEMARKETINGSTEUERUNG_CAMPAIGN_H AS CA
        ON      L.CAMPAIGN_H_SK = CA.CAMPAIGN_H_SK
    LEFT JOIN
        CTE_PC
        ON CA.CAMPAIGN_ID = CTE_PC.CAMP_ID
    WHERE TO_DATE(CONVERT_TZ(C.EVENT_CREATED_AT_UTC,'UTC','CET')) BETWEEN ADD_YEARS(CURRENT_DATE,-2) AND CURRENT_DATE
    -- Erweiterter BOT Filter, folgt noch
    AND C.BOT = FALSE
    AND CTE_PC.PLANNING_CONTEXT_NAME IN ('Private Network', 'AWIN')
)

SELECT
    PRT_PC.REPORTING_DATE
    , PRT_PC.PLANNING_CONTEXT_CODE
    , PRT_PC.PLANNING_CONTEXT_NAME
    , PRT_PC.CHANNEL
    , PRT_PC.CAMP_ID
    , PRT_PC.SOURCE_SYSTEM
    , 0 AS IMPRESSIONS
    , SUM(CLICKS) AS CLICKS
    , SUM(COST_EURO) AS COST_EURO
    , CASE
        WHEN
            INSTR(PRT_PC.CAMP_ID, '-TW.BC-') > 0
            OR INSTR(PRT_PC.CAMP_ID, '-PF.BC-') > 0
            THEN 2
        WHEN
            INSTR(PRT_PC.CAMP_ID, '-W.BC-') > 0
            OR INSTR(PRT_PC.CAMP_ID, '-F.BC-') > 0
            OR (INSTR(PRT_PC.CAMP_ID, '-SS.AG-') > 0 AND INSTR(PRT_PC.CAMP_ID, '-D.C-') > 0)
            OR INSTR(PRT_PC.CAMP_ID, '-SES.C-') > 0
            THEN 3
        ELSE 1
    END AS BUDGET_LOGIC
    ,CASE
        WHEN LOCAL.BUDGET_LOGIC = 1 THEN 1
        WHEN LOCAL.BUDGET_LOGIC = 3 THEN 0
        WHEN INSTR(PRT_PC.CAMP_ID, '.WS-') > 0 THEN 1 - REGEXP_SUBSTR(REGEXP_SUBSTR(CAMP_ID, '(\d+)\.WS'), '\d+') / 100
        WHEN INSTR(PRT_PC.CAMP_ID, '.FS-') > 0 THEN 1 - REGEXP_SUBSTR(REGEXP_SUBSTR(CAMP_ID, '(\d+)\.FS'), '\d+') / 100
        ELSE NULL
    END AS BUDGET_LOGIC_SHARE
FROM PRT_PC
GROUP BY
    PRT_PC.REPORTING_DATE
    , PRT_PC.PLANNING_CONTEXT_CODE
    , PRT_PC.PLANNING_CONTEXT_NAME
    , PRT_PC.CHANNEL
    , PRT_PC.CAMP_ID
    , PRT_PC.SOURCE_SYSTEM
    , LOCAL.BUDGET_LOGIC
    , LOCAL.BUDGET_LOGIC_SHARE
;
